### ISSUE TITLE
"latest" tag on Docker Hub targets arm64

### ISSUE THREAD

**Issue by tedcook94** [tborychowski/courier#6] opened 2021-12-15 23:40 UTC
The current "latest" container on Docker Hub targets arm64 instead of amd64, which seems to be a change from previous images.

I'm guessing this was done by mistake, but if ARM is the preferred platform going forward, a "latest-amd" tag for the equivalent version targeting x86_64 would be much appreciated.

**Comment by tborychowski** [comment] 2021-12-16 00:24
duplicate of #3

**Closed as completed by tborychowski** 2021-12-16 00:24 UTC
